version: "3"

services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src:/var/www/html:cached
      - ./letsencrypt/etc:/var/www/letsencrypt:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./http-pwd/etc/.htpasswd:/etc/nginx/.htpasswd:cached
      - ./http-pwd/bin/setnginxpwd:/var/www/html/bin/setnginxpwd:cached

  phpfpm:
    volumes: *appvolumes
