#!/bin/bash
set -o errexit

DOMAIN=${1:-local-magento-test.net}
VERSION=${2:-2.4.3-p3}
EDITION=${3:-community}
ADMIN_USER=${4}
ADMIN_PWD=${5}

echo "Starting installation..."

rm -rf .git

echo "Installing markshust docker"

curl -s https://raw.githubusercontent.com/dk4software/docker-magento/mage2.4.3/lib/template | bash

rm -rf .git

git init -qqq

git remote add origin https://github.com/dk4software/magento-local-setup

git fetch origin mage2.4.3 -qqq

git checkout origin/mage2.4.3 -- local

cp -r local/* ./
rm -rf local

rm -rf .git

echo "Installing Magento"

bin/download "${VERSION}" "${EDITION}" \
   && bin/setup "${DOMAIN}" \
   && bin/setuplocal "$ADMIN_USER" "$ADMIN_PWD"
